### ISSUE TITLE
Julian's Todo's

### ISSUE THREAD

**Issue by juliandierker** [juliandierker/yUOShi#249]
- [x] studIP bugs #242 #243

- [ ] #244 (vielleicht)

- [ ] Grading und Aufgabenzuweisung  

- [ ] Aufgabe lösen (Wie oft kann ein Student die Aufgabe bearbeiten)

- [x] HCI-Report in Issues übertragen (Thea ansprechpartner)

- [x] Zeitplanung mit Sebastian
